//Playback Actions
export const NEXT_ASSET = 'NEXT_ASSET';
export const PAUSE = 'PAUSE';
export const PLAY = 'PLAY';
export const PREVIOUS_ASSET = 'PREVIOUS_ASSET';
export const SET_ASSET_INDEX = 'SET_ASSET_INDEX';
export const SET_FREQUENCY = 'SET_FREQUENCY';
export const SET_VIEWPORT_SIZE = 'SET_VIEWPORT_SIZE';

//Fetch Actions
export const FETCH_MANIFEST_FAILED = 'FETCH_MANIFEST_FAILED';
export const FETCH_MANIFEST_REQUESTED = 'FETCH_MANIFEST_REQUESTED';
export const FETCH_MANIFEST_SUCCEEDED = 'FETCH_MANIFEST_SUCCEEDED';
