//Keyboard Actions
export const DOWN_KEY_PRESSED = 'DOWN_KEY_PRESSED';
export const LEFT_KEY_PRESSED = 'LEFT_KEY_PRESSED';
export const ENTER_KEY_PRESSED = 'ENTER_KEY_PRESSED';
export const RIGHT_KEY_PRESSED = 'RIGHT_KEY_PRESSED';
export const UNUSED_KEY_PRESSED = 'UNUSED_KEY_PRESSED';
export const UP_KEY_PRESSED = 'UP_KEY_PRESSED';

//Playback Actions
export const NEXT_ASSET = 'NEXT_ASSET';
export const PAUSE = 'PAUSE';
export const PLAY = 'PLAY';
export const PREVIOUS_ASSET = 'PREVIOUS_ASSET';
export const SET_ASSET_INDEX = 'SET_ASSET_INDEX';
export const SET_FREQUENCY = 'SET_FREQUENCY';
export const SET_VIEWPORT_SIZE = 'SET_VIEWPORT_SIZE';

//Fetch Actions
export const FETCH_DIRECTORY_FAILED = 'FETCH_DIRECTORY_FAILED';
export const FETCH_DIRECTORY_REQUESTED = 'FETCH_DIRECTORY_REQUESTED';
export const FETCH_DIRECTORY_SUCCEEDED = 'FETCH_DIRECTORY_SUCCEEDED';
export const FETCH_MANIFEST_FAILED = 'FETCH_MANIFEST_FAILED';
export const FETCH_MANIFEST_REQUESTED = 'FETCH_MANIFEST_REQUESTED';
export const FETCH_MANIFEST_SUCCEEDED = 'FETCH_MANIFEST_SUCCEEDED';
